source('patchCluster.R')
makePointsLocation(10, makeIsoGrid, dist_=3, noiseFactor=0.1)
identical(rnorm, makeIsoGrid)
source('patchCluster.R')
makePointsLocation(10, makeIsoGrid, dist_=3, noiseFactor=0.1)
?exists
source('patchCluster.R')
makePointsLocation(10, makeIsoGrid, dist_=3, noiseFactor=0.1)
traceback()
source('patchCluster.R')
makePointsLocation(10, makeIsoGrid, dist_=3, noiseFactor=0.1)
traceback()
source('patchCluster.R')
makePointsLocation(10, makeIsoGrid, dist_=3, noiseFactor=0.1)
plot(makePointsLocation(10, makeIsoGrid, dist_=3, noiseFactor=0.1))
cor(iris[-5])
source('samples.R')
sampler()
source('samples.R')
sampler()
sampler(ptsFun=makeIsoGrid, dist_=1, noiseFactor=0.1)
source('samples.R')
sampler(reps=10000, ptsFun=makeIsoGrid, dist_=1, noiseFactor=0.1)
x <- sampler(reps=10000, ptsFun=makeIsoGrid, dist_=1, noiseFactor=0.1)
source('samples.R')
??file
source('samples.R')
source('samples.R')
dir(pattern='Samp')
labs <- paste('iso', c(0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.8, 1, 2, 3)
)
labs
labs <- paste('iso', c(0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.8, 1, 2, 3), sep='')
labs
labs <- c(labs, 'runif', 'rnorm', 'rlnorm', 'pareto')
labs
trat <- rep(labs, each=1e4)
length(trat)
length(labs(
length(labs)
trat
labs
dir(pattern='Samp')
dir(pattern='Samp')
trat <- as.factor(trat)
levels(trat)
tablaTrats <- cbind(trat, 0)
dim(tablaTrats)
head(tablaTrats)
tablaTrats <- data.frame(trat=trat, fitStep=0)
dim(tablaTrats)
head(tablaTrats)
load('isoSamp_0.05.RData')
fitStep <- isoSamp_0.05$stepFit
rm(isoSamp_0.05)
load('isoSamp_0.1.RData')
fitStep <- c(fitStep, isoSamp_0.1$stepFit)
ls()
isoSamp_0.1 <- isoSamp
rm(isoSamp)
save(isoSamp_0.1, file='isoSamp_0.1.RData')
fitStep <- c(fitStep, isoSamp_0.1$stepFit)
length(fitStep)
rm(isoSamp_0.1)
load('isoSamp_0.2.RData')
fitStep <- c(fitStep, isoSamp_0.2$stepFit)
rm(isoSamp_0.2)
fitStep <- c(fitStep, isoSamp_0.3$stepFit)
load('isoSamp_0.3.RData')
fitStep <- c(fitStep, isoSamp_0.3$stepFit)
rm(isoSamp_0.3)
load('isoSamp_0.4.RData')
fitStep <- c(fitStep, isoSamp_0.4$stepFit)
rm(isoSamp_0.4)
load('isoSamp_0.5.RData')
fitStep <- c(fitStep, isoSamp_0.5$stepFit)
rm(isoSamp_0.5)
load('isoSamp_0.8.RData')
fitStep <- c(fitStep, isoSamp_0.8$stepFit)
rm(isoSamp_0.8)
load('isoSamp_1.RData')
fitStep <- c(fitStep, isoSamp_1$stepFit)
rm(isoSamp_1)
load('isoSamp_.RData')
load('isoSamp_2.RData')
fitStep <- c(fitStep, isoSamp_2$stepFit)
rm(isoSamp_2)
load('isoSamp_3.RData')
fitStep <- c(fitStep, isoSamp_3$stepFit)
rm(isoSamp_3)
load('uniSamp.RData')
fitStep <- c(fitStep, uniSamp$stepFit)
rm(uniSamp)
load('rnoSamp.RData')
fitStep <- c(fitStep, rnoSamp$stepFit)
rm(rnoSamp)
load('rnlSamp.RData')
fitStep <- c(fitStep, rnlSamp$stepFit)
rm(rnlSamp)
load('parSamp.RData')
fitStep <- c(fitStep, parSamp$stepFit)
rm(parSamp)
length(fitStep)
tablaTrats <- data.frame(trat=trat, stepFIt=fitStep)
tablaTrats <- data.frame(trat=trat, stepFit=fitStep)
plot(tablaTrats)
patchCluster(20, makeIsoGrid, dist_=1, noiseFactor=3)
patchCluster(20, makeIsoGrid, dist_=1, noiseFactor=3)
patchCluster(20, makeIsoGrid, dist_=1, noiseFactor=3)
patchCluster(20, makeIsoGrid, dist_=1, noiseFactor=3)
patchCluster(20, makeIsoGrid, dist_=1, noiseFactor=3)
patchCluster(20, makeIsoGrid, dist_=1, noiseFactor=3)
patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
source('patchCluster.R')
patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
source('patchCluster.R')
patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
patchCluster(20, makeIsoGrid, dist_=1, noiseFactor=3)
patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
stepFun
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
by(tablaTrats$stepFit, tablaTrats$trat, summary)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=8)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=8)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=8)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=8)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=8)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=3)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=.1)
x <- patchCluster(200, makeIsoGrid, dist_=1, noiseFactor=.01)
x$ca$fit
ls()
x$ca$fit
stepSS(1.0047, x=x$ca$movDist, y=x$ca$epatch,
min(x$ca$epatch)
max(x$ca$epatch)
stepSS(1.0047, x=x$ca$movDist, y=x$ca$epatch, min=1, max=196)
stepSS(1.0047, x=x$ca$movDist, y=x$ca$epatch, min=1, max=196)/200
length(x$ca$epatch)
str(x)
x$ca$epatch
stepSS(1.0047, x=x$ca$movDist, y=x$ca$epatch, min=1, max=196)/196
x$ca$fit
stepSS(1.0047, x=x$ca$movDist, y=x$ca$epatch, min=1, max=196)/197
stepSS(1.0047, x=x$ca$movDist, y=x$ca$epatch, min=1, max=196)/196
history(500)
savehistory(file='historia.R')
